language: node_js
dist: trusty
node_js:
  - node
addons:
  chrome: stable
  browserstack:
    username: xuexb1
    access_key:
      secure: "J/w5BzoliBGi0g+FsHBmn+aXYk1Q1YOXIECVrKt0ZJGusdN4GNaAS1oAG3Jc53BHa2CsCpCLtk06q21OXNPWADEwYmmbffNlJeQwYniJp4yHSanRg42UiPWhZ/7cWZGHdQGURHv8Np7B4n0wxThGJvk2gZiGwCKbXVeeGXK93NDaqamjKPqBojmeZQz05IvVC9H0xqwaePGyiHp+KASqZfEi2wIHiHLI64/fcJ+KcVVHA/+CmIGHytASOk9KPco+hTbnL/cgMv+HSu9ghP6TSsfXp5FTeLRplOjQ5Sljqstp6mRtRBXxbE1Ajy+H297qYixnfyVo9BC3bZFSkS3+nJAdImIB7HSKxmjGkBmhIdBBBym8/APSLPvalGaPTZjVqEbxcpEKkx4jQVXEPhefxAmRFrEXwS6VATScRlRNoloUrpXQV7sQ8GZWhVjUCYXf6CLcRCOagEL6uPZ3gW99Dpk5fhzGpcc01vR+Aq8g7xvUUnI4kKgknAUgDlviXOqYGORQPqs2WUCURFBrkyfKWUsIm7GRo2Wxif4S+t5sJJT3J/Qu96IB62ArEZZ0KhfTkHDqPp8+LbVGlklHtXtYYU0kpROO4b7JfzJNOBtGSL2p6ROyYBdjaZztvgW1QO/LKGxAMvXfWyERyahwnEclPULz23LV0FFM9nSU9tsJeT0="
env:
  global:
    BROWSER_STACK_USERNAME: xuexb1
    secure: "BZxjMgAOgwlWLtdCpaYDmBIdyCj/1vhJJs6Azi/d/xJJ+Ej9Bd5PyNyLW6HPAvJF3L105d4J5FxXwotSGGSNQQ72KQzFD86IhlP/arQWzU0E6fLkz30ZDAZRINimV8KWQZGcHbsrC/T5PjE3yqGC3Io0TofE0Nw/VzVpLkhkZpOupkOWHHN/n4uU/5tMwZKBlFEPEENMX4xD0NjbPQVe4yxR6eAQmP+xdmzJtDigHGSlWhCR7NMDciamzddkQKadBbJu8FU99K94QXb4rRowO02o69cKsFm52mQc7rbL2Y2oSN6ZQWBm7KIIB8NafyUt/RjfQtBK8ghEOBkqQtbD9dr9YsmyPhONicm62VzyDDU3V/uayXOlqdBslFwPfwkCZsDf1P0ubDs41/NUbtaFnmOC+LXjEklJmNM/uluzkLGe75LSnT4f7kZNdLj79AOGtPhaQGNpV9XPgOIkUmXc7EFi0uUTe/Cj3FdS2VIp2Y0ZN+A+n3w8jLT0Y5xOkr9CLWG9WTAw9OdWg4mh0ZrXECkUlrZPAUy6IosT/8dXUsqZAoWDoJHojrWPf810zKM7rHcYl7wGTKrqWYyh2BnVIgy1pXOV1mDFC0MSnEP8Gdvb43W5dHb0uOFYbMorMxoNWo2r+sb9hmkBX8+Td5PNAS7hOTTtvdJijTmN4c5jPuY="
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run test:cov && npm run test:sauce
after_script: 
  - npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage