language: node_js
dist: trusty
node_js:
  - node
addons:
  chrome: stable
  browserstack:
    username: xuexb1
  jwt:
    secure: "kHy8Y2KrpdIk8/4YFS1lW7xyWHlutCb+4ngZfaTSUm6sLDB2npVgW3VCnJJ8Qt8OCR3OnalqY9PqCW8qhvApIOZslIYf+Exi9+KhLrMtw1olhbihuQD1zQTkGsT+E+/XMEmy9+pADIfaNMYxG05bamWSNhdNwZDEa9PI454Jpl0/WKDZZ3I6BedQWuQnTH3XfIG7igt8szLttKDZhm5njbnosO6K3taIWFZPEkeGOZQgD/6BShUDVCFLIsKHgBaTIga5MWqlHKfrlUOhbpvAgFsfyOCnBjEpD3wtvyIMysRUhc8YqpIAovedq2Go/PWer85cjTUfKzg6v8ZNzpkJIisz+FKp307Y+DYKBPzur9SKSrIYalKzJ03pRwVhyMQzKDcd1Y/ONWqot98ZBsrM3i1Nd0JY25uiAsYdFWPPhdy58SwA3FWy5i0N70louZrih5i0jH9GHhIARROIckndbMCZpGX26drj3ApILETl05LzDlLcmflT4pMtshuTSdfLxTBoGFLrF4JrMD1Vx+NqfRp2DPnNV/4I9Th8W7yZpsOAqeqa5L8AgUd1bDHGOJtVK6rokRNySn5W6CUrum0GA6VVOL2of+Q28Er+YYR2pGuGXXfePzPV2kjyG+jeHuT00ZiNVWkvQer5X1JnpRfSbXMrp7fJDum7zNB6as+io9I="
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run test:cov && npm run test:sauce
after_script: 
  - npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage