language: node_js
dist: trusty
node_js:
  - node
addons:
  chrome: stable
  browserstack:
    username: xuexb1
    access_key:
      secure: "J/w5BzoliBGi0g+FsHBmn+aXYk1Q1YOXIECVrKt0ZJGusdN4GNaAS1oAG3Jc53BHa2CsCpCLtk06q21OXNPWADEwYmmbffNlJeQwYniJp4yHSanRg42UiPWhZ/7cWZGHdQGURHv8Np7B4n0wxThGJvk2gZiGwCKbXVeeGXK93NDaqamjKPqBojmeZQz05IvVC9H0xqwaePGyiHp+KASqZfEi2wIHiHLI64/fcJ+KcVVHA/+CmIGHytASOk9KPco+hTbnL/cgMv+HSu9ghP6TSsfXp5FTeLRplOjQ5Sljqstp6mRtRBXxbE1Ajy+H297qYixnfyVo9BC3bZFSkS3+nJAdImIB7HSKxmjGkBmhIdBBBym8/APSLPvalGaPTZjVqEbxcpEKkx4jQVXEPhefxAmRFrEXwS6VATScRlRNoloUrpXQV7sQ8GZWhVjUCYXf6CLcRCOagEL6uPZ3gW99Dpk5fhzGpcc01vR+Aq8g7xvUUnI4kKgknAUgDlviXOqYGORQPqs2WUCURFBrkyfKWUsIm7GRo2Wxif4S+t5sJJT3J/Qu96IB62ArEZZ0KhfTkHDqPp8+LbVGlklHtXtYYU0kpROO4b7JfzJNOBtGSL2p6ROyYBdjaZztvgW1QO/LKGxAMvXfWyERyahwnEclPULz23LV0FFM9nSU9tsJeT0="
env:
  global:
    secure: "bXMqKtSp2FR02sT9UDaDVznrYkwk0WJ6bEyZGEbuLiuDzp1lCJ62LeXMoz7Ai1PhteWwj4RhCmSGZMn0I9t4E0Due+VF5EdI80WZc6GS3jjjSizYrBmoyE3vp8qjJ8I8UTqtOqSxZqgjAMfwMJCtCGBOKRjiEiJoiCYvCg+/4iHjs9q++FfEh/1k5V9jvTANAvcGqrrfjLSbpFEGWF8VM20miZuEmW9ozsH1q4wqA17xN+OZE88bjgC09neX/muoyiZJrPkCs3IZglSTPgFy+v3oZmwD0NBpw/m2OThEz86puG3iwdwvMRLs3eidjJaXaeV17YhcoxRUkUF0rrSO+A1Gt9Bs5iosGovFqgxu/WSGcGB2JdEIGZZd/0H7GUMqpc/qTveIXJRn5TXlCl79m9EH5cqYiqiGW1xqnlJNhyWzu3Gn0D3ubNeMLBTpcZfJcPl9yhLpIEJQk8Bn2r67+bzwFExX8+3rE26H4pqvcQs13CgO2318RH21Fdg67zS9UyVp6yZ+cTo3jK0wfxYdkFtdO4Rn3rCvQUHrfbxrBS6DEw0AFAbrDphVLxt0/Z86n6Q0FwzW9Z4ucLjSPEEOFt43/Y9errm8lSvHVRStiBGby35OkX7uundA8sANfyw4OAzgYNRB8d5vfTAXFgS92EBk+3PlLMzvEiP7eXQdCGE="
  global:
    BROWSER_STACK_USERNAME: xuexb1
sudo: false
cache:
  directories:
    node_modules
script:
  npm run test:cov && npm run test:sauce
after_script: 
  npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage