language: node_js
dist: trusty
node_js:
  - node
addons:
  chrome: stable
  browserstack:
    username: xuexb1
    access_key:
      secure: "c7QDfJNilo7wkhXbz8vihOMN6bmaGGz37E60XUf8UPvxUFf45Tmjan4V0w1aNrn4bAxEtU157kCrWG1hV0bGvgtCK2mG9ITFA4MgMsV1EiLbXVdUvoTUzgof9KP/XMKQYTyri1Z8KoOR4feuyC7QhaLWfxc4mWazQ4IGRpC3q+Mp4HCGMHnXh9NBujbkv5AWeiuz6XLkyQGtO2lG/VCNBcERULunFm+kCHjzCeFlkxIM/inJEL66ZIUBMCXpzLGwXWd7dY/NSrqTDct4IECXusJPCLOlf9+miL5s54kb7XVAaTrV0CjuvVlpCcRFixgZtkSWP0RhI6HFJ8d0kZgpctT4nlc+FvCbougPF80bJSQx8fW8RV803tVQrivK+lU33tEOjH+tNhVG1/smTnsYBAfuCa/Q2oecUMK92tyCrMal+0Vvs682oYsAg9rb0OmsObJhLsIKetwfFhnzDckEDJOfcLPLvZ3tfz0xXKfVP46PeDbxFyXMgfg0sV5wMmxdKu3xQ6JgmeB9qa3DQ8Bk0dPwIdXa5dBa1BsAcHzViX2Qv8smULPYnWJHMxbkTrhCu1Fw35mioFIPn22yuykvMj2Cc40byWCkkBjw+gxr7DVz25NRnSwweH36GE2kTB6wGiOueYFte/yXqG29UjNIUnqLaTooylBOYcXIPtsuu9o="
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run test:cov && npm run test:sauce
after_script: 
  - npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage