language: node_js
dist: trusty
node_js:
  - node
addons:
  chrome: stable
  browserstack:
    username: xuexb1
    access_key:
      secure: "MheTE/ezD5M7FfMYp86xgYvEpiduUI9iO+ezlav5uZNN1OQwU+7cVg90Zh41xlonCRU+RtaipJMuy15mwGUqZ9EQc5cxrzzIeDSlMy5tu/vFudTUTKXp65JjM47qVs9u4yZ49Q0YPD7ZG5y2sKzZE6G8n1C0xF9AhaSJ/eFKfNHyCVXgAaaRabNHPmumxqz7qZfz8YGNt1rD3XcUB+enDWDYNWkFPryWgdMYNeFekhV0HKXWWAZMC3cxYPJIg8Ho2K6TGQA1DDXU9+H6WBupqhQ7E/tLjTcsia5vzZehmTNiXo2sqiFreG7yL2MI+RNop7D298Zk8gzME2LFtk3vnOqOOeAXPaMNAQrcfjHIOCdmM3yM2UuIgcLFtPDQsVfOweGDKEHN3UuEYj3R9BihOGo433zlTO5ta4y3vNjI1VOFl6GHEjL8o87zcLra0yXYasz1oV2wsYiWui4rt90Qv5oSCVFIZf+tUk0uJ/gVlD7QdtvIyWUZ8wgHX00/L9uYGw3QLYcSadz+v0VpsBQkJdOVQ+RXc4OvKg9zq8Sr2bo/IlQFBENPM9/S6oY1aABVkWJUL7pyFfhnVSlIJwDXWG5Y9ULN+jlyGt6eTC5+XNQvwtwtwa2zI8puoymDM8vIYx9VkTEhbGB/t6LlZD3jdTZuF35xR3fW2Gec8ZNwvHE="
env:
  global:
    BROWSER_STACK_USERNAME: xuexb1
    secure: "QL/KW7+grlUltRUv5rb62ol7GJNP5HqyOsHF5QC20Xw3o8FcrdRrPFD3fjD2WSjeXekTf8exh1ci6byuqzTjnTBKlhF0SCY3jc1xA7HCu4IHIe+1PkOHwOL7PhwQjBZUUO7Am9bcYR5KEOmhzCZMLu+HsuJfGjENEaeIyxS9DRL6ssMw8Y9JsqPFKMNKEXsR1JnlORsq5rBMu5gS+oCWDuiEoaT+2hIFnqk8K8QLVM78ut3+bBU4IeOHYJN6AI5b3/k9Gd8AMe73ucN/PCC6BSUlK3sJyqcEGq72YgaSYJyz1rs/ZS6CMGVrrrQjcZQq4gZ7RiGTSVy6ZLCFkG3qj8pQOi32QjFYMDGpNmbhlEuqOzlOSFPLfhzb+LPW7hmlSCkIlc69V/ZqkarObiQYXxHinb3JCWBbBgWcKaOChYWhepYvZCkZIbIw9SFdvs9RFVodyc1Fr7wkSNowNKkfH6b2qzExEBrO2VP/CY4n7MTv2gPIfKYWCX4FdNx1A6L3NHSqj3Y641PoV88EZaUBW/XH3OBdXhX+0RHpjCdFYgev1abwFtTnyyc06xveF7qfwgnJ7NBiqfDpvBaaVGS03q0DNe9LtAJo7UnyIsuqRo0Y5cggek+VKhFHJ9fjb6lNpu8XL770R+SJEHM7Jfa/z/2W0ZRnBsLWsa7cSR2AXuM="
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run test:cov && npm run test:sauce
after_script: 
  - npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage